version: "3"
services:
  app:
      container_name: c3
      image: faizdjauhar/c3-microservices
      restart: always
      build: .
      ports:
        - "80:80"
      links:
        - db
  db:
      container_name: mongo
      image: mongo:latest
      ports:
        - '27017:27017'

        